version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8005:8005"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8005"



volumes:
  pg_data:
    driver: local