"""fixed constraint table

Revision ID: 7aedab7e3b7a
Revises: 0a3d913e3d41
Create Date: 2025-04-08 16:07:19.894012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7aedab7e3b7a"
down_revision: Union[str, None] = "0a3d913e3d41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_seats_positive", "tables", type_="check")
    op.create_check_constraint("check_seats_positive", "tables", "seats >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_seats_positive", "tables", type_="check")
    op.create_check_constraint("check_seats_positive", "tables", "seats > 0")
    # ### end Alembic commands ###
